//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoolify.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schoolify.Common.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        public static string Academic {
            get {
                return ResourceManager.GetString("Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A class with the selected subject, term, and section already exists.
        /// </summary>
        public static string ClassAlreadyExists {
            get {
                return ResourceManager.GetString("ClassAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class created successfully.
        /// </summary>
        public static string ClassCreated {
            get {
                return ResourceManager.GetString("ClassCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class deleted successfully.
        /// </summary>
        public static string ClassDeleted {
            get {
                return ResourceManager.GetString("ClassDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes not found.
        /// </summary>
        public static string ClassesNotFound {
            get {
                return ResourceManager.GetString("ClassesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not found.
        /// </summary>
        public static string ClassNotFound {
            get {
                return ResourceManager.GetString("ClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom.
        /// </summary>
        public static string Classroom {
            get {
                return ResourceManager.GetString("Classroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom created successfully.
        /// </summary>
        public static string ClassroomCreated {
            get {
                return ResourceManager.GetString("ClassroomCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom deleted successfully.
        /// </summary>
        public static string ClassroomDeleted {
            get {
                return ResourceManager.GetString("ClassroomDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom not found.
        /// </summary>
        public static string ClassroomNotFound {
            get {
                return ResourceManager.GetString("ClassroomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string Classrooms {
            get {
                return ResourceManager.GetString("Classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms not found.
        /// </summary>
        public static string ClassroomsNotFound {
            get {
                return ResourceManager.GetString("ClassroomsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom Type.
        /// </summary>
        public static string ClassroomType {
            get {
                return ResourceManager.GetString("ClassroomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom type created successfully.
        /// </summary>
        public static string ClassroomTypeCreated {
            get {
                return ResourceManager.GetString("ClassroomTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom type deleted successfully.
        /// </summary>
        public static string ClassroomTypeDeleted {
            get {
                return ResourceManager.GetString("ClassroomTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom type not found.
        /// </summary>
        public static string ClassroomTypeNotFound {
            get {
                return ResourceManager.GetString("ClassroomTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom Types.
        /// </summary>
        public static string ClassroomTypes {
            get {
                return ResourceManager.GetString("ClassroomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom types not found.
        /// </summary>
        public static string ClassroomTypesNotFound {
            get {
                return ResourceManager.GetString("ClassroomTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom type updated successfully.
        /// </summary>
        public static string ClassroomTypeUpdated {
            get {
                return ResourceManager.GetString("ClassroomTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classroom updated successfully.
        /// </summary>
        public static string ClassroomUpdated {
            get {
                return ResourceManager.GetString("ClassroomUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Schedule.
        /// </summary>
        public static string ClassSchedule {
            get {
                return ResourceManager.GetString("ClassSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class schedule created successfully.
        /// </summary>
        public static string ClassScheduleCreated {
            get {
                return ResourceManager.GetString("ClassScheduleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class schedule deleted successfully.
        /// </summary>
        public static string ClassScheduleDeleted {
            get {
                return ResourceManager.GetString("ClassScheduleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class schedule not found.
        /// </summary>
        public static string ClassScheduleNotFound {
            get {
                return ResourceManager.GetString("ClassScheduleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Schedules.
        /// </summary>
        public static string ClassSchedules {
            get {
                return ResourceManager.GetString("ClassSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class schedules not found.
        /// </summary>
        public static string ClassSchedulesNotFound {
            get {
                return ResourceManager.GetString("ClassSchedulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class schedule updated successfully.
        /// </summary>
        public static string ClassScheduleUpdated {
            get {
                return ResourceManager.GetString("ClassScheduleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class updated successfully.
        /// </summary>
        public static string ClassUpdated {
            get {
                return ResourceManager.GetString("ClassUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Of Week .
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department created successfully.
        /// </summary>
        public static string DepartmentCreated {
            get {
                return ResourceManager.GetString("DepartmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department deleted successfully.
        /// </summary>
        public static string DepartmentDeleted {
            get {
                return ResourceManager.GetString("DepartmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department updated successfully.
        /// </summary>
        public static string DepartmentUpdated {
            get {
                return ResourceManager.GetString("DepartmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string Enrollment {
            get {
                return ResourceManager.GetString("Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment already exists.
        /// </summary>
        public static string EnrollmentAlreadyExists {
            get {
                return ResourceManager.GetString("EnrollmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment created successfully.
        /// </summary>
        public static string EnrollmentCreated {
            get {
                return ResourceManager.GetString("EnrollmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment deleted successfully.
        /// </summary>
        public static string EnrollmentDeleted {
            get {
                return ResourceManager.GetString("EnrollmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment not found.
        /// </summary>
        public static string EnrollmentNotFound {
            get {
                return ResourceManager.GetString("EnrollmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments.
        /// </summary>
        public static string Enrollments {
            get {
                return ResourceManager.GetString("Enrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enrollments found.
        /// </summary>
        public static string EnrollmentsNotFound {
            get {
                return ResourceManager.GetString("EnrollmentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Status.
        /// </summary>
        public static string EnrollmentStatus {
            get {
                return ResourceManager.GetString("EnrollmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment updated successfully.
        /// </summary>
        public static string EnrollmentUpdated {
            get {
                return ResourceManager.GetString("EnrollmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolment Date.
        /// </summary>
        public static string EnrolmentDate {
            get {
                return ResourceManager.GetString("EnrolmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string Error403Description {
            get {
                return ResourceManager.GetString("Error403Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Error403Heading {
            get {
                return ResourceManager.GetString("Error403Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 - Access Denied.
        /// </summary>
        public static string Error403Title {
            get {
                return ResourceManager.GetString("Error403Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for might have been removed, renamed, or is temporarily unavailable..
        /// </summary>
        public static string Error404Description {
            get {
                return ResourceManager.GetString("Error404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Page Not Found.
        /// </summary>
        public static string Error404Heading {
            get {
                return ResourceManager.GetString("Error404Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Page Not Found.
        /// </summary>
        public static string Error404Title {
            get {
                return ResourceManager.GetString("Error404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred on the server. Please try again later.
        /// </summary>
        public static string Error500Description {
            get {
                return ResourceManager.GetString("Error500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        public static string Error500Heading {
            get {
                return ResourceManager.GetString("Error500Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - Server Error.
        /// </summary>
        public static string Error500Title {
            get {
                return ResourceManager.GetString("Error500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination.
        /// </summary>
        public static string Examination {
            get {
                return ResourceManager.GetString("Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Item.
        /// </summary>
        public static string FeeItem {
            get {
                return ResourceManager.GetString("FeeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Items.
        /// </summary>
        public static string FeeItems {
            get {
                return ResourceManager.GetString("FeeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Structure.
        /// </summary>
        public static string FeeStructure {
            get {
                return ResourceManager.GetString("FeeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee structure already exists.
        /// </summary>
        public static string FeeStructureAlreadyExists {
            get {
                return ResourceManager.GetString("FeeStructureAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee structure created successfully.
        /// </summary>
        public static string FeeStructureCreated {
            get {
                return ResourceManager.GetString("FeeStructureCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee structure deleted successfully.
        /// </summary>
        public static string FeeStructureDeleted {
            get {
                return ResourceManager.GetString("FeeStructureDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee structure not found.
        /// </summary>
        public static string FeeStructureNotFound {
            get {
                return ResourceManager.GetString("FeeStructureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Structures.
        /// </summary>
        public static string FeeStructures {
            get {
                return ResourceManager.GetString("FeeStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fee structures found.
        /// </summary>
        public static string FeeStructuresNotFound {
            get {
                return ResourceManager.GetString("FeeStructuresNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee structure updated successfully.
        /// </summary>
        public static string FeeStructureUpdated {
            get {
                return ResourceManager.GetString("FeeStructureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalScore.
        /// </summary>
        public static string FinalScore {
            get {
                return ResourceManager.GetString("FinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Year Score.
        /// </summary>
        public static string FinalYearScore {
            get {
                return ResourceManager.GetString("FinalYearScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forth Name.
        /// </summary>
        public static string ForthName {
            get {
                return ResourceManager.GetString("ForthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduated.
        /// </summary>
        public static string Graduated {
            get {
                return ResourceManager.GetString("Graduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        public static string Guardian {
            get {
                return ResourceManager.GetString("Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian created successfully.
        /// </summary>
        public static string GuardianCreated {
            get {
                return ResourceManager.GetString("GuardianCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian deleted successfully.
        /// </summary>
        public static string GuardianDeleted {
            get {
                return ResourceManager.GetString("GuardianDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian not found.
        /// </summary>
        public static string GuardianNotFound {
            get {
                return ResourceManager.GetString("GuardianNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardians.
        /// </summary>
        public static string Guardians {
            get {
                return ResourceManager.GetString("Guardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Type.
        /// </summary>
        public static string GuardianType {
            get {
                return ResourceManager.GetString("GuardianType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian type created successfully.
        /// </summary>
        public static string GuardianTypeCreated {
            get {
                return ResourceManager.GetString("GuardianTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian type deleted successfully.
        /// </summary>
        public static string GuardianTypeDeleted {
            get {
                return ResourceManager.GetString("GuardianTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian type not found.
        /// </summary>
        public static string GuardianTypeNotFound {
            get {
                return ResourceManager.GetString("GuardianTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Types.
        /// </summary>
        public static string GuardianTypes {
            get {
                return ResourceManager.GetString("GuardianTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guardian types found.
        /// </summary>
        public static string GuardianTypesNotFound {
            get {
                return ResourceManager.GetString("GuardianTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian type updated successfully.
        /// </summary>
        public static string GuardianTypeUpdated {
            get {
                return ResourceManager.GetString("GuardianTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian updated successfully.
        /// </summary>
        public static string GuardianUpdated {
            get {
                return ResourceManager.GetString("GuardianUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        public static string Installment {
            get {
                return ResourceManager.GetString("Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installments.
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be earlier than end date.
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be later than start time.
        /// </summary>
        public static string InvalidTimeRange {
            get {
                return ResourceManager.GetString("InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Teacher.
        /// </summary>
        public static string IsMainTeacher {
            get {
                return ResourceManager.GetString("IsMainTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Order.
        /// </summary>
        public static string LevelOrder {
            get {
                return ResourceManager.GetString("LevelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Teacher.
        /// </summary>
        public static string MainTeacher {
            get {
                return ResourceManager.GetString("MainTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks Obtained.
        /// </summary>
        public static string MarksObtained {
            get {
                return ResourceManager.GetString("MarksObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Score.
        /// </summary>
        public static string MaxScore {
            get {
                return ResourceManager.GetString("MaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min score must be less than max score.
        /// </summary>
        public static string MinMaxError {
            get {
                return ResourceManager.GetString("MinMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Score.
        /// </summary>
        public static string MinScore {
            get {
                return ResourceManager.GetString("MinScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Fees.
        /// </summary>
        public static string NetFees {
            get {
                return ResourceManager.GetString("NetFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoClass.
        /// </summary>
        public static string NoClass {
            get {
                return ResourceManager.GetString("NoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fee items found.
        /// </summary>
        public static string NoFeeItemsFound {
            get {
                return ResourceManager.GetString("NoFeeItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teachers assigned.
        /// </summary>
        public static string NoTeachersAssigned {
            get {
                return ResourceManager.GetString("NoTeachersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score range overlaps with existing range.
        /// </summary>
        public static string OverlapError {
            get {
                return ResourceManager.GetString("OverlapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period created successfully.
        /// </summary>
        public static string PeriodCreated {
            get {
                return ResourceManager.GetString("PeriodCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period deleted successfully.
        /// </summary>
        public static string PeriodDeleted {
            get {
                return ResourceManager.GetString("PeriodDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period not found.
        /// </summary>
        public static string PeriodNotFound {
            get {
                return ResourceManager.GetString("PeriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods not found.
        /// </summary>
        public static string PeriodsNotFound {
            get {
                return ResourceManager.GetString("PeriodsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period updated successfully.
        /// </summary>
        public static string PeriodUpdated {
            get {
                return ResourceManager.GetString("PeriodUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between 0 and 100.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Types.
        /// </summary>
        public static string RoomTypes {
            get {
                return ResourceManager.GetString("RoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Stage.
        /// </summary>
        public static string SchoolStage {
            get {
                return ResourceManager.GetString("SchoolStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School stage created successfully.
        /// </summary>
        public static string SchoolStageCreated {
            get {
                return ResourceManager.GetString("SchoolStageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School stage deleted successfully.
        /// </summary>
        public static string SchoolStageDeleted {
            get {
                return ResourceManager.GetString("SchoolStageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School stage not found.
        /// </summary>
        public static string SchoolStageNotFound {
            get {
                return ResourceManager.GetString("SchoolStageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Stages.
        /// </summary>
        public static string SchoolStages {
            get {
                return ResourceManager.GetString("SchoolStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School stages not found.
        /// </summary>
        public static string SchoolStagesNotFound {
            get {
                return ResourceManager.GetString("SchoolStagesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School stage updated successfully.
        /// </summary>
        public static string SchoolStageUpdated {
            get {
                return ResourceManager.GetString("SchoolStageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Year.
        /// </summary>
        public static string SchoolYear {
            get {
                return ResourceManager.GetString("SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School year created successfully.
        /// </summary>
        public static string SchoolYearCreated {
            get {
                return ResourceManager.GetString("SchoolYearCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School year deleted successfully.
        /// </summary>
        public static string SchoolYearDeleted {
            get {
                return ResourceManager.GetString("SchoolYearDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School year not found.
        /// </summary>
        public static string SchoolYearNotFound {
            get {
                return ResourceManager.GetString("SchoolYearNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Years.
        /// </summary>
        public static string SchoolYears {
            get {
                return ResourceManager.GetString("SchoolYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School years not found.
        /// </summary>
        public static string SchoolYearsNotFound {
            get {
                return ResourceManager.GetString("SchoolYearsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School year updated successfully.
        /// </summary>
        public static string SchoolYearUpdated {
            get {
                return ResourceManager.GetString("SchoolYearUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Range.
        /// </summary>
        public static string ScoreRange {
            get {
                return ResourceManager.GetString("ScoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score range created successfully.
        /// </summary>
        public static string ScoreRangeCreated {
            get {
                return ResourceManager.GetString("ScoreRangeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score range deleted successfully.
        /// </summary>
        public static string ScoreRangeDeleted {
            get {
                return ResourceManager.GetString("ScoreRangeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score range not found.
        /// </summary>
        public static string ScoreRangeNotFound {
            get {
                return ResourceManager.GetString("ScoreRangeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Ranges.
        /// </summary>
        public static string ScoreRanges {
            get {
                return ResourceManager.GetString("ScoreRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score ranges not found.
        /// </summary>
        public static string ScoreRangesNotFound {
            get {
                return ResourceManager.GetString("ScoreRangesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score range updated successfully.
        /// </summary>
        public static string ScoreRangeUpdated {
            get {
                return ResourceManager.GetString("ScoreRangeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section created successfully.
        /// </summary>
        public static string SectionCreated {
            get {
                return ResourceManager.GetString("SectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section deleted successfully.
        /// </summary>
        public static string SectionDeleted {
            get {
                return ResourceManager.GetString("SectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not found.
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections found.
        /// </summary>
        public static string SectionsNotFound {
            get {
                return ResourceManager.GetString("SectionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section updated successfully.
        /// </summary>
        public static string SectionUpdated {
            get {
                return ResourceManager.GetString("SectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Class --.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Classroom --.
        /// </summary>
        public static string SelectClassroom {
            get {
                return ResourceManager.GetString("SelectClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Day --.
        /// </summary>
        public static string SelectDay {
            get {
                return ResourceManager.GetString("SelectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Department --.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Enrollment Status --.
        /// </summary>
        public static string SelectEnrollmentStatus {
            get {
                return ResourceManager.GetString("SelectEnrollmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Gender --.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Period --.
        /// </summary>
        public static string SelectPeriod {
            get {
                return ResourceManager.GetString("SelectPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Room Type --.
        /// </summary>
        public static string SelectRoomType {
            get {
                return ResourceManager.GetString("SelectRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select School Stage --.
        /// </summary>
        public static string SelectSchoolStage {
            get {
                return ResourceManager.GetString("SelectSchoolStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select School Year --.
        /// </summary>
        public static string SelectSchoolYear {
            get {
                return ResourceManager.GetString("SelectSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Section --.
        /// </summary>
        public static string SelectSection {
            get {
                return ResourceManager.GetString("SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Student --.
        /// </summary>
        public static string SelectStudent {
            get {
                return ResourceManager.GetString("SelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Subject --.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Teacher --.
        /// </summary>
        public static string SelectTeacher {
            get {
                return ResourceManager.GetString("SelectTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Term --.
        /// </summary>
        public static string SelectTerm {
            get {
                return ResourceManager.GetString("SelectTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Year Level --.
        /// </summary>
        public static string SelectYearLevel {
            get {
                return ResourceManager.GetString("SelectYearLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error occurred.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Academic Record.
        /// </summary>
        public static string StudentAcademicRecord {
            get {
                return ResourceManager.GetString("StudentAcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Academic Records.
        /// </summary>
        public static string StudentAcademicRecords {
            get {
                return ResourceManager.GetString("StudentAcademicRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Class.
        /// </summary>
        public static string StudentClass {
            get {
                return ResourceManager.GetString("StudentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Classes.
        /// </summary>
        public static string StudentClasses {
            get {
                return ResourceManager.GetString("StudentClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student class not found.
        /// </summary>
        public static string StudentClassNotFound {
            get {
                return ResourceManager.GetString("StudentClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student created successfully.
        /// </summary>
        public static string StudentCreated {
            get {
                return ResourceManager.GetString("StudentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student deleted successfully.
        /// </summary>
        public static string StudentDeleted {
            get {
                return ResourceManager.GetString("StudentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Exam Result.
        /// </summary>
        public static string StudentExamResult {
            get {
                return ResourceManager.GetString("StudentExamResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Exam Results.
        /// </summary>
        public static string StudentExamResults {
            get {
                return ResourceManager.GetString("StudentExamResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Guardian.
        /// </summary>
        public static string StudentGuardian {
            get {
                return ResourceManager.GetString("StudentGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student guardian not found.
        /// </summary>
        public static string StudentGuardianNotFound {
            get {
                return ResourceManager.GetString("StudentGuardianNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Guardians.
        /// </summary>
        public static string StudentGuardians {
            get {
                return ResourceManager.GetString("StudentGuardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found.
        /// </summary>
        public static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No students found.
        /// </summary>
        public static string StudentsNotFound {
            get {
                return ResourceManager.GetString("StudentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student updated successfully.
        /// </summary>
        public static string StudentUpdated {
            get {
                return ResourceManager.GetString("StudentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Year Level.
        /// </summary>
        public static string StudentYearLevel {
            get {
                return ResourceManager.GetString("StudentYearLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student year level not found.
        /// </summary>
        public static string StudentYearLevelNotFound {
            get {
                return ResourceManager.GetString("StudentYearLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Year Levels.
        /// </summary>
        public static string StudentYearLevels {
            get {
                return ResourceManager.GetString("StudentYearLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Class.
        /// </summary>
        public static string SubjectClass {
            get {
                return ResourceManager.GetString("SubjectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Classes.
        /// </summary>
        public static string SubjectClasses {
            get {
                return ResourceManager.GetString("SubjectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Class Teacher.
        /// </summary>
        public static string SubjectClassTeacher {
            get {
                return ResourceManager.GetString("SubjectClassTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject class teacher assignment already exists.
        /// </summary>
        public static string SubjectClassTeacherAlreadyExists {
            get {
                return ResourceManager.GetString("SubjectClassTeacherAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject class teacher assignment created successfully.
        /// </summary>
        public static string SubjectClassTeacherCreated {
            get {
                return ResourceManager.GetString("SubjectClassTeacherCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject class teacher assignment deleted successfully.
        /// </summary>
        public static string SubjectClassTeacherDeleted {
            get {
                return ResourceManager.GetString("SubjectClassTeacherDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject class teacher assignment not found.
        /// </summary>
        public static string SubjectClassTeacherNotFound {
            get {
                return ResourceManager.GetString("SubjectClassTeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Class Teachers.
        /// </summary>
        public static string SubjectClassTeachers {
            get {
                return ResourceManager.GetString("SubjectClassTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject class teacher assignments found.
        /// </summary>
        public static string SubjectClassTeachersNotFound {
            get {
                return ResourceManager.GetString("SubjectClassTeachersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject class teacher assignment updated successfully.
        /// </summary>
        public static string SubjectClassTeacherUpdated {
            get {
                return ResourceManager.GetString("SubjectClassTeacherUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject created successfully.
        /// </summary>
        public static string SubjectCreated {
            get {
                return ResourceManager.GetString("SubjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject deleted successfully.
        /// </summary>
        public static string SubjectDeleted {
            get {
                return ResourceManager.GetString("SubjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject not found.
        /// </summary>
        public static string SubjectNotFound {
            get {
                return ResourceManager.GetString("SubjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subjects found.
        /// </summary>
        public static string SubjectsNotFound {
            get {
                return ResourceManager.GetString("SubjectsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject updated successfully.
        /// </summary>
        public static string SubjectUpdated {
            get {
                return ResourceManager.GetString("SubjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher created successfully!.
        /// </summary>
        public static string TeacherCreatedSuccess {
            get {
                return ResourceManager.GetString("TeacherCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher deleted successfully!.
        /// </summary>
        public static string TeacherDeletedSuccess {
            get {
                return ResourceManager.GetString("TeacherDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher updated successfully!.
        /// </summary>
        public static string TeacherUpdatedSuccess {
            get {
                return ResourceManager.GetString("TeacherUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term created successfully.
        /// </summary>
        public static string TermCreated {
            get {
                return ResourceManager.GetString("TermCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term deleted successfully.
        /// </summary>
        public static string TermDeleted {
            get {
                return ResourceManager.GetString("TermDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term not found.
        /// </summary>
        public static string TermNotFound {
            get {
                return ResourceManager.GetString("TermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Number.
        /// </summary>
        public static string TermNumber {
            get {
                return ResourceManager.GetString("TermNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms not found.
        /// </summary>
        public static string TermsNotFound {
            get {
                return ResourceManager.GetString("TermsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term updated successfully.
        /// </summary>
        public static string TermUpdated {
            get {
                return ResourceManager.GetString("TermUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name.
        /// </summary>
        public static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fees.
        /// </summary>
        public static string TotalFees {
            get {
                return ResourceManager.GetString("TotalFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        public static string Transferred {
            get {
                return ResourceManager.GetString("Transferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the validation errors and try again..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Level.
        /// </summary>
        public static string YearLevel {
            get {
                return ResourceManager.GetString("YearLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year level created successfully.
        /// </summary>
        public static string YearLevelCreated {
            get {
                return ResourceManager.GetString("YearLevelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year level deleted successfully.
        /// </summary>
        public static string YearLevelDeleted {
            get {
                return ResourceManager.GetString("YearLevelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year level not found.
        /// </summary>
        public static string YearLevelNotFound {
            get {
                return ResourceManager.GetString("YearLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Levels.
        /// </summary>
        public static string YearLevels {
            get {
                return ResourceManager.GetString("YearLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year levels not found.
        /// </summary>
        public static string YearLevelsNotFound {
            get {
                return ResourceManager.GetString("YearLevelsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year level updated successfully.
        /// </summary>
        public static string YearLevelUpdated {
            get {
                return ResourceManager.GetString("YearLevelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
