// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schoolify.DataAccess.Data;

#nullable disable

namespace Schoolify.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Schoolify.Common.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(100m);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7313),
                            IsDeleted = false,
                            MaxScore = 100.00m,
                            NameAr = "رياضيات - الصف العاشر أ",
                            NameEn = "Math - Grade 10 A",
                            SubjectId = 1,
                            TeacherId = 1,
                            TermId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7314)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7440),
                            IsDeleted = false,
                            MaxScore = 100.00m,
                            NameAr = "فيزياء - الصف العاشر أ",
                            NameEn = "Physics - Grade 10 A",
                            SubjectId = 2,
                            TeacherId = 1,
                            TermId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7440)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7445),
                            IsDeleted = false,
                            MaxScore = 100.00m,
                            NameAr = "إنجليزي - الصف العاشر أ",
                            NameEn = "English - Grade 10 A",
                            SubjectId = 3,
                            TeacherId = 2,
                            TermId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7446)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ClassId", "PeriodId", "DayOfWeek")
                        .IsUnique();

                    b.HasIndex("ClassroomId", "PeriodId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            ClassroomId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8284),
                            DayOfWeek = 0,
                            IsDeleted = false,
                            PeriodId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8285)
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            ClassroomId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8288),
                            DayOfWeek = 0,
                            IsDeleted = false,
                            PeriodId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8289)
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            ClassroomId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8292),
                            DayOfWeek = 1,
                            IsDeleted = false,
                            PeriodId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8293)
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            ClassroomId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8295),
                            DayOfWeek = 1,
                            IsDeleted = false,
                            PeriodId = 4,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8296)
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            ClassroomId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8299),
                            DayOfWeek = 2,
                            IsDeleted = false,
                            PeriodId = 5,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8300)
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            ClassroomId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8303),
                            DayOfWeek = 2,
                            IsDeleted = false,
                            PeriodId = 6,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8304)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7083),
                            IsDeleted = false,
                            NameAr = "الفصل A1",
                            NameEn = "Classroom A1",
                            RoomTypeId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7084)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7088),
                            IsDeleted = false,
                            NameAr = "الفصل A2",
                            NameEn = "Classroom A2",
                            RoomTypeId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7089)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7091),
                            IsDeleted = false,
                            NameAr = "معمل العلوم 1",
                            NameEn = "Science Lab 1",
                            RoomTypeId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7092)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7095),
                            IsDeleted = false,
                            NameAr = "معمل الحاسوب 1",
                            NameEn = "Computer Lab 1",
                            RoomTypeId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7096)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7099),
                            IsDeleted = false,
                            NameAr = "المكتبة",
                            NameEn = "Library Room",
                            RoomTypeId = 4,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7100)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7103),
                            IsDeleted = false,
                            NameAr = "القاعة الكبرى",
                            NameEn = "Auditorium",
                            RoomTypeId = 5,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7104)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.ClassroomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ClassroomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7203),
                            IsDeleted = false,
                            NameAr = "فصل دراسي",
                            NameEn = "Regular Classroom",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7204)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7207),
                            IsDeleted = false,
                            NameAr = "معمل علوم",
                            NameEn = "Science Laboratory",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7208)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7210),
                            IsDeleted = false,
                            NameAr = "معمل حاسوب",
                            NameEn = "Computer Lab",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7211)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7213),
                            IsDeleted = false,
                            NameAr = "مكتبة",
                            NameEn = "Library Room",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7214)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7217),
                            IsDeleted = false,
                            NameAr = "قاعة متعددة الاستخدام",
                            NameEn = "Auditorium",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7217)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5548),
                            IsDeleted = false,
                            NameAr = "العلوم",
                            NameEn = "Science",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5552)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5556),
                            IsDeleted = false,
                            NameAr = "اللغات",
                            NameEn = "Languages",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5557)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5560),
                            IsDeleted = false,
                            NameAr = "الدراسات الاجتماعية",
                            NameEn = "Social Studies",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5561)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5773),
                            IsDeleted = false,
                            NameAr = "الرياضيات",
                            NameEn = "Mathematics",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(5774)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Guardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Guardians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7740),
                            EmailAddress = "mohamed.ali@email.com",
                            FirstName = "Mohamed",
                            ForthName = "Ahmed",
                            IsDeleted = false,
                            PhoneNumber = "0911111111",
                            SecondName = "Ali",
                            ThirdName = "Hassan",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7741)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7746),
                            EmailAddress = "fatima.ibrahim@email.com",
                            FirstName = "Fatima",
                            ForthName = "Youssef",
                            IsDeleted = false,
                            PhoneNumber = "0922222222",
                            SecondName = "Ibrahim",
                            ThirdName = "Omar",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7747)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7750),
                            EmailAddress = "abdullah.mahmoud@email.com",
                            FirstName = "Abdullah",
                            ForthName = "Ali",
                            IsDeleted = false,
                            PhoneNumber = "0933333333",
                            SecondName = "Mahmoud",
                            ThirdName = "Hassan",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7751)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.GuardianType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("GuardianTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6980),
                            IsDeleted = false,
                            NameAr = "الأب",
                            NameEn = "Father",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6981)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6984),
                            IsDeleted = false,
                            NameAr = "الأم",
                            NameEn = "Mother",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6985)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6987),
                            IsDeleted = false,
                            NameAr = "ولي أمر",
                            NameEn = "Guardian",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6988)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6842),
                            EndTime = new TimeSpan(0, 8, 45, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة الأولى",
                            NameEn = "Period 1",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6843)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6851),
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة الثانية",
                            NameEn = "Period 2",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 8, 45, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6852)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6855),
                            EndTime = new TimeSpan(0, 10, 15, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة الثالثة",
                            NameEn = "Period 3",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 9, 30, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6856)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6860),
                            EndTime = new TimeSpan(0, 10, 45, 0, 0),
                            IsDeleted = false,
                            NameAr = "الفسحة",
                            NameEn = "Break",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 10, 15, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6861)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6864),
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة الرابعة",
                            NameEn = "Period 4",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 10, 45, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6865)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6869),
                            EndTime = new TimeSpan(0, 12, 15, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة الخامسة",
                            NameEn = "Period 5",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 11, 30, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6870)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6874),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsDeleted = false,
                            NameAr = "الحصة السادسة",
                            NameEn = "Period 6",
                            SchoolYearId = 1,
                            StartTime = new TimeSpan(0, 12, 15, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6875)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.SchoolStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("SchoolStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6392),
                            IsDeleted = false,
                            NameAr = "الابتدائية",
                            NameEn = "Primary",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6392)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6396),
                            IsDeleted = false,
                            NameAr = "المتوسطة",
                            NameEn = "Middle",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6396)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6399),
                            IsDeleted = false,
                            NameAr = "الثانوية",
                            NameEn = "Secondary",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6400)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8194),
                            EndDate = new DateOnly(2025, 6, 30),
                            IsDeleted = false,
                            NameAr = "العام الدراسي 2024-2025",
                            NameEn = "2024-2025",
                            StartDate = new DateOnly(2024, 9, 1),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8195)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8200),
                            EndDate = new DateOnly(2026, 6, 30),
                            IsDeleted = false,
                            NameAr = "العام الدراسي 2025-2026",
                            NameEn = "2025-2026",
                            StartDate = new DateOnly(2025, 9, 1),
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8201)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.ScoreRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Grade")
                        .IsUnique();

                    b.ToTable("ScoreRanges", t =>
                        {
                            t.HasCheckConstraint("CK_ScoreRange_MinMax", "[MinScore] <= [MaxScore]");

                            t.HasCheckConstraint("CK_ScoreRange_ValidRange", "[MinScore] >= 0 AND [MaxScore] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8095),
                            Grade = "A",
                            IsDeleted = false,
                            MaxScore = 100m,
                            MinScore = 90m,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8095)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8101),
                            Grade = "B",
                            IsDeleted = false,
                            MaxScore = 89.99m,
                            MinScore = 80m,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8102)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8105),
                            Grade = "C",
                            IsDeleted = false,
                            MaxScore = 79.99m,
                            MinScore = 70m,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8106)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8109),
                            Grade = "D",
                            IsDeleted = false,
                            MaxScore = 69.99m,
                            MinScore = 60m,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8110)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8113),
                            Grade = "F",
                            IsDeleted = false,
                            MaxScore = 59.99m,
                            MinScore = 0m,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8114)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EnrolmentDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7524),
                            DateOfBirth = new DateOnly(2010, 5, 10),
                            EnrolmentDate = new DateOnly(2025, 9, 1),
                            FirstName = "Ali",
                            ForthName = "Ahmed",
                            Gender = 1,
                            IsDeleted = false,
                            SecondName = "Mohamed",
                            ThirdName = "Hassan",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7525)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7539),
                            DateOfBirth = new DateOnly(2011, 8, 15),
                            EnrolmentDate = new DateOnly(2025, 9, 1),
                            FirstName = "Sara",
                            ForthName = "Youssef",
                            Gender = 2,
                            IsDeleted = false,
                            SecondName = "Ibrahim",
                            ThirdName = "Omar",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7540)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7545),
                            DateOfBirth = new DateOnly(2009, 12, 20),
                            EnrolmentDate = new DateOnly(2024, 9, 1),
                            FirstName = "Omar",
                            ForthName = "Hassan",
                            Gender = 1,
                            IsDeleted = false,
                            SecondName = "Ali",
                            ThirdName = "Mahmoud",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7545)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MarksObtained")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("StudentClasses", t =>
                        {
                            t.HasCheckConstraint("CK_StudentClass_Marks", "[MarksObtained] IS NULL OR ([MarksObtained] >= 0 AND [MarksObtained] <= 100)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7629),
                            IsDeleted = false,
                            MarksObtained = 85.50m,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7630)
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7635),
                            IsDeleted = false,
                            MarksObtained = 78.00m,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7636)
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7639),
                            IsDeleted = false,
                            MarksObtained = 92.00m,
                            StudentId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7640)
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7643),
                            IsDeleted = false,
                            MarksObtained = 88.50m,
                            StudentId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7644)
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7647),
                            IsDeleted = false,
                            MarksObtained = 74.00m,
                            StudentId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7648)
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7651),
                            IsDeleted = false,
                            StudentId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7652)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentGuardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardianId")
                        .HasColumnType("int");

                    b.Property<int>("GuardianTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.HasIndex("GuardianTypeId");

                    b.HasIndex("StudentId", "GuardianId", "GuardianTypeId")
                        .IsUnique();

                    b.ToTable("StudentGuardians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7835),
                            GuardianId = 1,
                            GuardianTypeId = 1,
                            IsDeleted = false,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7835)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7838),
                            GuardianId = 2,
                            GuardianTypeId = 2,
                            IsDeleted = false,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7839)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7842),
                            GuardianId = 1,
                            GuardianTypeId = 1,
                            IsDeleted = false,
                            StudentId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7843)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7845),
                            GuardianId = 2,
                            GuardianTypeId = 2,
                            IsDeleted = false,
                            StudentId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7846)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentYearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalYearScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("YearLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("YearLevelId");

                    b.HasIndex("StudentId", "YearLevelId", "SchoolYearId")
                        .IsUnique();

                    b.ToTable("StudentYearLevels", t =>
                        {
                            t.HasCheckConstraint("CK_StudentYearLevel_Score", "[FinalYearScore] IS NULL OR ([FinalYearScore] >= 0 AND [FinalYearScore] <= 100)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8016),
                            FinalYearScore = 85.50m,
                            IsDeleted = false,
                            SchoolYearId = 1,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8016),
                            YearLevelId = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8021),
                            FinalYearScore = 92.00m,
                            IsDeleted = false,
                            SchoolYearId = 1,
                            StudentId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8021),
                            YearLevelId = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8025),
                            IsDeleted = false,
                            SchoolYearId = 2,
                            StudentId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(8026),
                            YearLevelId = 11
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6287),
                            DepartmentId = 1,
                            IsDeleted = false,
                            NameAr = "الرياضيات",
                            NameEn = "Mathematics",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6288)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6291),
                            DepartmentId = 1,
                            IsDeleted = false,
                            NameAr = "الفيزياء",
                            NameEn = "Physics",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6292)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6295),
                            DepartmentId = 1,
                            IsDeleted = false,
                            NameAr = "الكيمياء",
                            NameEn = "Chemistry",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6296)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6298),
                            DepartmentId = 2,
                            IsDeleted = false,
                            NameAr = "اللغة الإنجليزية",
                            NameEn = "English",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6299)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6302),
                            DepartmentId = 2,
                            IsDeleted = false,
                            NameAr = "اللغة العربية",
                            NameEn = "Arabic",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6302)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6305),
                            DepartmentId = 3,
                            IsDeleted = false,
                            NameAr = "التاريخ",
                            NameEn = "History",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6306)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6308),
                            DepartmentId = 3,
                            IsDeleted = false,
                            NameAr = "الجغرافيا",
                            NameEn = "Geography",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6309)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7920),
                            EmailAddress = "ahmed.ali@schoolify.com",
                            FirstName = "Ahmed",
                            ForthName = "Mohamed",
                            Gender = 0,
                            HireDate = new DateOnly(1, 1, 1),
                            IsDeleted = false,
                            PhoneNumber = "0912345678",
                            SecondName = "Ali",
                            ThirdName = "Hassan",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7921)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7926),
                            EmailAddress = "sara.ibrahim@schoolify.com",
                            FirstName = "Sara",
                            ForthName = "Yusuf",
                            Gender = 0,
                            HireDate = new DateOnly(1, 1, 1),
                            IsDeleted = false,
                            PhoneNumber = "0923456789",
                            SecondName = "Ibrahim",
                            ThirdName = "Omar",
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(7927)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6757),
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            SchoolYearId = 1,
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermNumber = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6758)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6766),
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            SchoolYearId = 1,
                            StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TermNumber = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6767)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.YearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SchoolStageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SchoolStageId");

                    b.ToTable("YearLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6507),
                            IsDeleted = false,
                            LevelOrder = 1,
                            NameAr = "الصف الأول",
                            NameEn = "Grade 1",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6617)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6622),
                            IsDeleted = false,
                            LevelOrder = 2,
                            NameAr = "الصف الثاني",
                            NameEn = "Grade 2",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6623)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6626),
                            IsDeleted = false,
                            LevelOrder = 3,
                            NameAr = "الصف الثالث",
                            NameEn = "Grade 3",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6627)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6630),
                            IsDeleted = false,
                            LevelOrder = 4,
                            NameAr = "الصف الرابع",
                            NameEn = "Grade 4",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6631)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6634),
                            IsDeleted = false,
                            LevelOrder = 5,
                            NameAr = "الصف الخامس",
                            NameEn = "Grade 5",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6635)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6638),
                            IsDeleted = false,
                            LevelOrder = 6,
                            NameAr = "الصف السادس",
                            NameEn = "Grade 6",
                            SchoolStageId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6639)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6642),
                            IsDeleted = false,
                            LevelOrder = 1,
                            NameAr = "الصف السابع",
                            NameEn = "Grade 7",
                            SchoolStageId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6643)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6646),
                            IsDeleted = false,
                            LevelOrder = 2,
                            NameAr = "الصف الثامن",
                            NameEn = "Grade 8",
                            SchoolStageId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6647)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6650),
                            IsDeleted = false,
                            LevelOrder = 3,
                            NameAr = "الصف التاسع",
                            NameEn = "Grade 9",
                            SchoolStageId = 2,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6651)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6654),
                            IsDeleted = false,
                            LevelOrder = 1,
                            NameAr = "الصف العاشر",
                            NameEn = "Grade 10",
                            SchoolStageId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6655)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6657),
                            IsDeleted = false,
                            LevelOrder = 2,
                            NameAr = "الصف الحادي عشر",
                            NameEn = "Grade 11",
                            SchoolStageId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6658)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6661),
                            IsDeleted = false,
                            LevelOrder = 3,
                            NameAr = "الصف الثاني عشر",
                            NameEn = "Grade 12",
                            SchoolStageId = 3,
                            UpdatedAt = new DateTime(2026, 6, 8, 20, 11, 2, 666, DateTimeKind.Utc).AddTicks(6662)
                        });
                });

            modelBuilder.Entity("Schoolify.Common.Models.Class", b =>
                {
                    b.HasOne("Schoolify.Common.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Term", "Term")
                        .WithMany("Classes")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Schoolify.Common.Models.ClassSchedule", b =>
                {
                    b.HasOne("Schoolify.Common.Models.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Classroom", "Classroom")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Period", "Period")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Classroom");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Classroom", b =>
                {
                    b.HasOne("Schoolify.Common.Models.ClassroomType", "RoomType")
                        .WithMany("Classrooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Period", b =>
                {
                    b.HasOne("Schoolify.Common.Models.SchoolYear", "SchoolYear")
                        .WithMany("Periods")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentClass", b =>
                {
                    b.HasOne("Schoolify.Common.Models.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Student", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentGuardian", b =>
                {
                    b.HasOne("Schoolify.Common.Models.Guardian", "Guardian")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.GuardianType", "GuardianType")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("GuardianTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Student", "Student")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");

                    b.Navigation("GuardianType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Schoolify.Common.Models.StudentYearLevel", b =>
                {
                    b.HasOne("Schoolify.Common.Models.SchoolYear", "SchoolYear")
                        .WithMany("StudentYearLevels")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.Student", "Student")
                        .WithMany("StudentYearLevels")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schoolify.Common.Models.YearLevel", "YearLevel")
                        .WithMany("StudentYearLevels")
                        .HasForeignKey("YearLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");

                    b.Navigation("YearLevel");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Subject", b =>
                {
                    b.HasOne("Schoolify.Common.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Term", b =>
                {
                    b.HasOne("Schoolify.Common.Models.SchoolYear", "SchoolYear")
                        .WithMany("Terms")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Schoolify.Common.Models.YearLevel", b =>
                {
                    b.HasOne("Schoolify.Common.Models.SchoolStage", "SchoolStage")
                        .WithMany("YearLevels")
                        .HasForeignKey("SchoolStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolStage");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Class", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Classroom", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("Schoolify.Common.Models.ClassroomType", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Department", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Guardian", b =>
                {
                    b.Navigation("StudentGuardians");
                });

            modelBuilder.Entity("Schoolify.Common.Models.GuardianType", b =>
                {
                    b.Navigation("StudentGuardians");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Period", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("Schoolify.Common.Models.SchoolStage", b =>
                {
                    b.Navigation("YearLevels");
                });

            modelBuilder.Entity("Schoolify.Common.Models.SchoolYear", b =>
                {
                    b.Navigation("Periods");

                    b.Navigation("StudentYearLevels");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Student", b =>
                {
                    b.Navigation("StudentClasses");

                    b.Navigation("StudentGuardians");

                    b.Navigation("StudentYearLevels");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Schoolify.Common.Models.Term", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Schoolify.Common.Models.YearLevel", b =>
                {
                    b.Navigation("StudentYearLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
